export const SET_CITY_LIST = 'SET_CITY_LIST';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const FETCH_ADD_CTY_FAIL = 'FETCH_ADD_CITY_FAIL';

export const SET_UNIT_TEMP_SUCCESS = 'SET_UNIT_TEMP_SUCCESS';
