export const SET_CITY_LIST = 'SET_CITY_LIST';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const SET_ACTION_MESSAGE = 'SET_ACTION_MESSAGE';


